version: "3.6"

services:
  app1:
    container_name: smtp1
    build: .
    ports:
      - "${HOST_PORT:-19081}:9081"
    restart: always

  # app2:
  #   container_name: smtp2
  #   build: .
  #   ports:
  #     - "${HOST_PORT:-19082}:9082"
  #   restart: always

  # app3:
  #   container_name: smtp3
  #   build: .
  #   ports:
  #     - "${HOST_PORT:-19083}:9083"
  #   restart: always